apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-environments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-environments
  template:
    metadata:
      labels:
        app: my-environments
    spec:
      containers:
        - name: my-environments
          image: PROJECT/IMAGE
